// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    lock: (name: string, _timeout: number, acquire: () => Promise<any>) => acquire(),
  },
  global: {
    headers: {
      'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
    }
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
    heartbeatIntervalMs: 10000,       // Send heartbeat every 10s (more frequent)
    reconnectAfterMs: (tries: number) => {
      // Aggressive reconnection: 100ms, 200ms, 500ms, 1s, 2s, 5s, 10s
      const delays = [100, 200, 500, 1000, 2000, 5000, 10000];
      return delays[Math.min(tries, delays.length - 1)];
    },
    timeout: 10000,                   // Timeout after 10s (faster detection)
  },
});